version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
      - "9229:9229"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: todo_db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app  # Mounts the host directory to the container
      - /usr/src/app/node_modules  # Ensures dependencies stay within the container
    command: npm run start:dev

volumes:
  pgdata:
